article/urls.py
from django.contrib import admin
from django.urls import path
# from views import index
from . import views

app_name = "article"
# create
# 32523523
urlpatterns = [
    path('create/', views.create, name="create"),
    path('deneme1/', views.about, name="deneme1"),
    path('deneme2/', views.index2, name="deneme2"),
    path('frontend_test/', views.frontend_test, name="frontend_test"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addarticle/', views.addArticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('', views.articles, name="articles"),
    path('comment/<int:id>', views.addComment, name="comment")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article.views import index, index2, about, detail
from django.conf import settings
from django.conf.urls.static import static

# http://127.0.0.1:8000/articles/create
# http://127.0.0.1:8000/articles/32523523
# http://127.0.0.1:8000/user
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name="index"),
                  path('index2', index2, name="index2"),
                  path('about/', about, name="about"),
                  path('articles/', include("article.urls")),
                  path('user/', include("user.urls")),
                  path('tinymce/', include('tinymce.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.my_login, name="login"),
    path('logout/', views.my_logout, name="logout"),
]

templates/includes/footer.html
<footer class="footer bg-dark fixed-bottom" style="height:5rem">
    <div class="container">
        <span class="text-muted">Reserved all right by Selçuk Akarın</span>
    </div>
</footer>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Nova Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Hakkımızda</a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">


            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}">Çıkış yap</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
            </li>
            {% endif %}

        </ul>

    </div>
</nav>