article/urls.py
from django.contrib import admin
from django.urls import path
# from views import index
from . import views

app_name = "article"
# create
# 32523523
urlpatterns = [
    path('create/', views.create, name="create"),
    path('deneme1/', views.about, name="deneme1"),
    path('deneme2/', views.index2, name="deneme2"),
    path('frontend_test/', views.frontend_test, name="frontend_test"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addarticle/', views.addArticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('', views.articles, name="articles"),
    path('comment/<int:id>', views.addComment, name="comment")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article.views import index, index2, about, detail
from django.conf import settings
from django.conf.urls.static import static

# http://127.0.0.1:8000/articles/create
# http://127.0.0.1:8000/articles/32523523
# http://127.0.0.1:8000/user
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name="index"),
                  path('index2', index2, name="index2"),
                  path('about/', about, name="about"),
                  path('articles/', include("article.urls")),
                  path('user/', include("user.urls")),
                  path('tinymce/', include('tinymce.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from tinymce import models as tinymce_models

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="YAZAR")
    title = models.CharField(max_length=50, verbose_name="BAŞLIK")
    content = RichTextField()
    content2 = tinymce_models.HTMLField()
    article_image = models.FileField(blank=True, null=True, verbose_name="Makaleye fotoğraf ekleyin")
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Makale", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="İsim")
    comment_content = models.CharField(max_length=200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article
from tinymce.widgets import TinyMCE

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = "__all__"
        exclude = ["author"]
        widgets = {'content': TinyMCE(attrs={'cols': 80, 'rows': 30})}

article/views.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404

from article.forms import ArticleForm
from article.models import Article, Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse


# Create your views here.


def index(request):
    users = User.objects.all()
    mylist = []
    for user in users:
        mylist.append(user.first_name)

    context = {
        "users": users,
        "mylist": mylist,
        "isim": "Ali",
        "yas": 18,
        "numbers": [1, 2, 3, 4, 5, 6, 7, 8],
        "coffees": {"latte": 25, "americano": 30, "çay": 15, "filtre kahve": 35}
    }
    return render(request, "index.html", context)


def index2(request):
    return render(request, "index2.html")


def about(request):
    return render(request, "about.html")


def detail(request, id):
    article = get_object_or_404(Article, id=id)
    # article = Article.objects.filter(id=id).first()
    comments = article.comments.all()
    context = {
        "article": article,
        "comments": comments
    }
    return render(request, "detail.html", context)


# @user_passes_test(lambda u: u.is_superuser)
@login_required(login_url="user:login")
def create(request):
    return render(request, "create.html")


def frontend_test(request):
    users = User.objects.all()
    return render(request, "frontend.html", {"users": users})


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.all()
    context = {
        "articles": articles,
        "site_admini": "selçuk akarın",
        "location": "istanbul",
        "meyveler": ["Elma", "Armut", "Vişne", "Hindistan Cevizi"]
    }
    return render(request, "dashboard.html", context)


@login_required(login_url="user:login")
def addArticle(request):
    # Post request
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        # author = form.cleaned_data.get("author")
        # title = form.cleaned_data.get("title")
        #
        # article = Article()
        # article.author = author
        # article.title = title
        # article.save()

        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Makaleniz başarıyla kaydedildi.")
        return redirect("article:dashboard")

    context = {
        "form": form
    }
    return render(request, "addArticle.html", context)


@login_required(login_url="user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()  # commit = True

        messages.success(request, "Makale başarıyla güncellendi.")
        return redirect("article:dashboard")
    return render(request, "update.html", {"form": form})


@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()

    messages.success(request, "Makele başarıyla silindi.")
    return redirect("article:dashboard")


def articles(request):
    keyword = request.GET.get("keyword")
    articles = Article.objects.all()
    if keyword:
        articles = Article.objects.filter(Q(title__contains=keyword) | Q(content__contains=keyword))

    return render(request, "articles.html", {"articles": articles})


def addComment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        new_comment = Comment()
        new_comment.comment_author = comment_author
        new_comment.comment_content = comment_content
        new_comment.article = article
        new_comment.save()
    return redirect(reverse("article:detail", kwargs={"id": id}))

templates/about.html
{% extends "layout.html" %}
{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>Selamlar Ben Selçuk</p>
{% endblock body %}

templates/addArticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row"> 
    <div class="col-md-6 offset-md-3">
        <form method="post" enctype="multipart/form-data">
            <h3>Makale Oluştur</h3>
            <hr>
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}

            <br>
            <button type="submit" class="btn btn-success">Kaydet</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}


<div class="row">
    <div class="col-lg-8 offset-2" style="text-align:center">
        <h3>Makaleler</h3>
        <hr>
        <form action="" method="GET">
            {% csrf_token %}
            <input type="text" name="keyword" class="input-sm">
            <button type="submit" class="btn btn-danger">Ara</button>
            <hr>
        </form>
    </div>
</div>

{% if articles %}
{% for article in articles %}
<div class="row">
    <div class="col-lg-8 offset-2">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"><h1 class="fw-bolder mb-1">{{ article.title }}</h1></a>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{ article.created_date }}</div>
                <!-- Author-->
                <p class="lead">{{ article.author }}</p>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}"
                                      alt="..."></figure>
            {% endif %}
            <!-- Post content-->
            <section class="mb-5">
                <div class="">
                    {{ article.content|safe|truncatewords:10 }}
                    <a href="{% url 'article:detail' article.id %}">read more</a>
                </div>
            </section>
        </article>
        <hr>
    </div>
</div>

{% endfor %}
{% else %}
<div class="row">
    <div class="col-lg-8 offset-2">
        <div class="alert alert-danger" role="alert">
            Makale bulunamadı
        </div>
    </div>
</div>
{% endif %}

<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
{% endblock body %}

templates/create.html
{% extends "layout.html" %}
{% block body %}
<h3>Create Sayfası</h3>
<hr>
<p>Burada bir şeyler create edilecek</p>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli Sayfası</h3>
<p>
    Hoşgeldiniz, <small>{{ request.user.username }}</small>
</p>
<hr>
{% if articles %}
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Yazar</th>
            <th scope="col">Başlık</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
        </tr>
        </thead>
        <tbody>
        {% for article in articles %}
        <tr>
            <td>{{ article.id }}</td>
            <td>{{ article.author }}</td>
            <td><a href="{% url 'article:detail' article.id %}">{{ article.title }}</a></td>
            <td>{{ article.created_date }}</td>
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-warning">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
{% else %}
    <div class="alert alert-danger" role="alert">
        Henüz bir makaleniz bulunmuyor.
    </div>
{% endif %}
<a href="{% url 'article:addarticle' %}" class="btn btn-danger">Makale Ekle</a>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
{% load static %}

<div class="row">
    <div class="col-lg-8 offset-2">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{ article.created_date }}</div>
                <!-- Author-->
                <p class="lead">{{ article.author }}</p>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <figure class="mb-4"><img class="img-fluid rounded "
                                      src="{{ article.article_image.url }}"
                                      alt="..."></figure>
            {% endif %}
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">{{ article.content|safe }}</p>
            </section>
        </article>
        <section class="mb-5">
            <h1>Yorum Ekle</h1>
            <hr>
            <div class="card bg-light">
                <div class="card-body">
                    <!-- Comment form-->
                    <form class="mb-4" method="post" action="{% url 'article:comment' article.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleInputEmail1">Yazar:</label>
                            <input type="text" class="form-control" id="exampleInputEmail1"
                                   aria-describedby="yazarHelp" placeholder="Yazar ismi"
                                   name="comment_author"
                            >
                        </div>

                        <div class="form-group">
                            <label>Yorum:</label>
                            <textarea class="form-control" rows="3" name="comment_content"
                                      placeholder="Lütfen yorumunuzu giriniz."
                                      data-sider-insert-id="3397cf06-3701-48fe-ae6b-569ca16c0cb5"
                                      data-sider-select-id="cab454df-7321-44da-a1f8-8bd3a783d2bc"
                            ></textarea>
                        </div>
                        <button class="btn btn-danger" type="submit">Ekle</button>

                    </form>
                    <!-- Comment with nested comments-->
                    {% for comment in comments %}
                    <div class="d-flex mb-4">
                        <!-- Parent comment-->
                        <div class="flex-shrink-0"><img class="rounded-circle mr-3" style="width:50px"
                                                        src="{% static 'avatar.png' %}" alt="...">
                        </div>
                        <div class="ms-3">
                            <div class="fw-bold">
                                <b>{{ comment.comment_author }}</b>
                                <br>
                                <sup>{{ comment.comment_date}}</sup>
                            </div>
                            {{ comment.comment_content }}

                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<p>
    {% if request.user.is_authenticated %}
        giriş yapılmış, {{ request.user.username }}
    {% else %}
        giriş yapılmamış
    {% endif %}
</p>

{% endblock body %}

templates/index2.html
{% extends "layout.html" %}

{% block body %}

<p>index2</p>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NovaAcademyDjangoBlog</title>
<!--    <link rel="stylesheet" href="{% static 'style2.css' %}">-->
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap4_0_0.css' %}">

</head>
<body>
    {% include "includes/navbar.html" %}
    <div class="container" style="margin-bottom: 10rem;">
        {% if messages %}
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} mt-3" {% endif %} role="alert">
                  {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block body %}
        {% endblock body %}

    </div>
    {% include "includes/footer.html" %}
    <script src="{% static 'js/jquery3_2_1.js' %}"></script>
<!--    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
<!--    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>-->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="post">
            <h3>Giriş Yap</h3>
            <hr>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="btn btn-success">Giriş Yap</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="post">
            <h3>Kayıt ol</h3>
            <hr>
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            ***********
            <!--                {% for field in form %}-->
            <!--                    {% for error in field.errors %}-->
            <!--                    <p>{{ error }}</p>-->
            <!--                    {% endfor %}-->
            <!--                {% endfor %}-->

                            {{ form.as_p }}
            <!--                {{ form|crispy }}-->
<!--            {% for field in form %}-->
<!--            <div class="fieldWrapper">-->
<!--                {{ field.label_tag }}-->
<!--                {{ field }}-->
<!--            </div>-->
<!--            {% endfor %}-->
            <br>
            <button type="submit" class="btn btn-danger">Kayıt ol</button>
        </form>
    </div>
</div>

<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>-->
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="post" enctype="multipart/form-data">
            <h3>Makale Güncelle</h3>
            <hr>
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}

            <br>
            <button type="submit" class="btn btn-success">Kaydet</button>
        </form>
    </div>
</div>

{% endblock body %}